# Generated by Django 5.1.4 on 2025-01-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_advertisementimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
