# Generated by Django 5.1.4 on 2025-01-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('Neqliyat', 'Neqliyat'), ('Daşınmaz Emlak', 'Daşınmaz Emlak'), ('Geyim', 'Geyim'), ('İş İlanları', 'İş İlanları'), ('elektronik', 'Elektronik')], max_length=50, null=True),
        ),
    ]
