# Generated by Django 5.1.4 on 2025-01-20 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_advertisement_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedilan',
            name='ilan',
        ),
        migrations.RemoveField(
            model_name='likedilan',
            name='user',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('Neqliyat', 'Neqliyat'), ('Daşınmaz Emlak', 'Daşınmaz Emlak'), ('Geyim', 'Geyim'), ('İş İlanları', 'İş İlanları'), ('Elektronik', 'Elektronik')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'advertisement')},
            },
        ),
        migrations.DeleteModel(
            name='Ilan',
        ),
        migrations.DeleteModel(
            name='LikedIlan',
        ),
    ]
