# Generated by Django 5.1.7 on 2025-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('Neqliyat', 'Neqliyat'), ('Daşinmaz Emlak', 'Daşinmaz Emlak'), ('Geyim', 'Geyim'), ('İş İlanlari', 'İş İlanlari'), ('Elektronik', 'Elektronik')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('sold', 'Satipldi'), ('pending', 'Beklemede')], default='active', max_length=10),
        ),
    ]
