# Generated by Django 5.1.7 on 2025-03-28 14:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
